events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Trang chu - Flask landing page
        location = / {
            proxy_pass http://landing:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # CTFd - tat ca route con lai
        location / {
            proxy_pass http://ctfd:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Challenge services
        location /web/sqli/        { proxy_pass http://web-sqli-easy:5001/; }
        location /web/xss/         { proxy_pass http://web-xss-easy:5002/; }
        location /web/idor/        { proxy_pass http://web-idor-medium:5003/; }
        location /web/ssti/        { proxy_pass http://web-ssti-hard:5004/; }
        location /crypto/caesar/   { proxy_pass http://crypto-caesar-easy:6001/; }
        location /forensics/stego/ { proxy_pass http://forensics-stego-easy:7001/; }
        location /re/strings/      { proxy_pass http://re-strings-easy:8001/; }
        location /re/xor/          { proxy_pass http://re-xor-easy:8002/; }
        location /re/base64/       { proxy_pass http://re-base64-easy:8003/; }
        location /pwn/bof/         { proxy_pass http://pwn-bof-easy:9001/; }
        location /pwn/ret2win/     { proxy_pass http://pwn-ret2win-easy:9002/; }
        location /misc/morse/      { proxy_pass http://misc-morse-easy:10001/; }
        location /osint/metadata/  { proxy_pass http://osint-metadata-easy:11001/; }
    }
}